---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# LassoBag

[LassoBag](https://github.com/likelet/LassoBag) provides an implementation of a CART frame for selecting markers from multiple models. A main application of this package is to screen limitted number of variables that are less dependent to train dataset. Basically, this packages was initially deveploped for adjust LASSO selected results from bootstrapped sample set. Variables with the highest frequency among the several selected result were considered as stable variables for differ sample set. However, it is usually hard to determine the cutoff in terms of frequency when applyed in a real dataset. In this package, we introduced a permutation test to obtain P-values of variables. In addition, it supports several multiple correction methods for P-value adjustment.

## Installation

You can install the released version of lassoBag from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("LassoBag")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("likelet/LassoBag")
```

